-- ----------------------------
-- Records of modulo
-- ----------------------------
INSERT INTO "public"."modulo" VALUES (1, NULL, 'Gestion de Usuarios Sigas', 'user_Modulo', 'person', 't', NULL);
INSERT INTO "public"."modulo" VALUES (2, '/rol', 'Perfiles', 'roles', 'dashboard', 't', 1);
INSERT INTO "public"."modulo" VALUES (3, '/usuario', 'Usuario', 'usuario', 'account_box', 't', 1);
INSERT INTO "public"."modulo" VALUES (4, '/usuario_profile', 'Perfil Usuario', 'perfil', 'dvr', 't', 1);
INSERT INTO "public"."modulo" VALUES (5, '/bitacora', 'Bitácora', 'bitacora', 'dvr', 't', 1);
INSERT INTO "public"."modulo" VALUES (6, '', 'Consultar', 'usuario_query', 'home', 'f', 3);
INSERT INTO "public"."modulo" VALUES (7, '/usuario_insert', 'Adicionar', 'usuario_insert', 'home', 'f', 3);
INSERT INTO "public"."modulo" VALUES (8, '/usuario_update', 'Actualizar', 'usuario_update', 'home', 'f', 3);
INSERT INTO "public"."modulo" VALUES (9, '/usuario_delete', 'Dar de Baja', 'usuario_delete', 'home', 'f', 3);
INSERT INTO "public"."modulo" VALUES (10, '', 'Consultar', 'rol_query', 'home', 'f', 2);
INSERT INTO "public"."modulo" VALUES (11, '/rol_insert', 'Adicionar', 'rol_insert', 'home', 'f', 2);
INSERT INTO "public"."modulo" VALUES (12, '/rol_update', 'Actualizar', 'rol_update', 'home', 'f', 2);
INSERT INTO "public"."modulo" VALUES (13, '/rol_delete', 'Dar de Baja', 'rol_delete', 'home', 'f', 2);
INSERT INTO "public"."modulo" VALUES (14, '', 'Consultar', 'bitacora_query', 'home', 'f', 5);
INSERT INTO "public"."modulo" VALUES (15, NULL, 'Gestion de Condominio', 'condominios', 'domain', 't', NULL);
INSERT INTO "public"."modulo" VALUES (16, '/condominio', 'Condominios', 'condominio', 'location_city', 't', 15);
INSERT INTO "public"."modulo" VALUES (17, '/nropase', 'Cant. de Tarjetas', 'nropase', 'credit_card', 't', 15);
INSERT INTO "public"."modulo" VALUES (18, '/usuarioCondominio', 'Usuarios', 'usuarioCondominio', 'assignment_ind', 't', 15);
INSERT INTO "public"."modulo" VALUES (19, '/areasocial', 'Areas Social', 'areasocial', 'account_balance', 't', 15);
INSERT INTO "public"."modulo" VALUES (20, '/domicilio', 'Domicilios', 'domicilio', 'home', 't', 15);
INSERT INTO "public"."modulo" VALUES (21, NULL, 'Gestion de Vehiculos', 'gvehiculos', 'book', 't', 15);
INSERT INTO "public"."modulo" VALUES (22, '/provper', 'Prov. Permanentes', 'provper', 'people', 't', 15);
INSERT INTO "public"."modulo" VALUES (23, '/residente', 'Residentes', 'residente', 'people_outline', 't', 15);
INSERT INTO "public"."modulo" VALUES (24, '/evento', 'Eventos', 'evento', 'event', 't', 15);
INSERT INTO "public"."modulo" VALUES (25, '/invitado', 'Invitados', 'invitado', 'person_add', 't', 15);
INSERT INTO "public"."modulo" VALUES (26, '/movimiento', 'Control y Registro Vehicular', 'movimiento', 'control_point', 't', 15);
INSERT INTO "public"."modulo" VALUES (27, '/movimiento_p', 'Control y Registro Peatonal', 'movimiento_p', 'control_point', 't', 15);
INSERT INTO "public"."modulo" VALUES (28, '/portero_virtual', 'Portero Virtual', 'portero_virtual', 'control_point', 't', 15);
INSERT INTO "public"."modulo" VALUES (29, '/reporte', 'Reportes', 'reporte', 'content_paste', 't', 15);
INSERT INTO "public"."modulo" VALUES (30, '/registros_c', 'Registros', 'registros_c', 'assignment', 't', 15);
INSERT INTO "public"."modulo" VALUES (31, '', 'Consultar', 'condominio_query', 'home', 'f', 16);
INSERT INTO "public"."modulo" VALUES (32, '/condominio_insert', 'Adicionar', 'condominio_insert', 'home', 'f', 16);
INSERT INTO "public"."modulo" VALUES (33, '/condominio_update', 'Actualizar', 'condominio_update', 'home', 'f', 16);
INSERT INTO "public"."modulo" VALUES (34, '/condominio_delete', 'Dar de Baja', 'condominio_delete', 'home', 'f', 16);
INSERT INTO "public"."modulo" VALUES (35, '/condominio_imprimir', 'Reportes', 'condominio_imprimir', 'home', 'f', 16);
INSERT INTO "public"."modulo" VALUES (36, '', 'Consultar', 'nropase_query', 'home', 'f', 17);
INSERT INTO "public"."modulo" VALUES (37, '/nropase_insert', 'Adicionar', 'nropase_insert', 'home', 'f', 17);
INSERT INTO "public"."modulo" VALUES (38, '/nropase_update', 'Actualizar', 'nropase_update', 'home', 'f', 17);
INSERT INTO "public"."modulo" VALUES (39, '/nropase_delete', 'Dar de Baja', 'nropase_delete', 'home', 'f', 17);
INSERT INTO "public"."modulo" VALUES (40, '/nropase_importar', 'Dar de Baja', 'nropase_importar', 'home', 'f', 17);
INSERT INTO "public"."modulo" VALUES (41, '/nropase_imprimir', 'Reportes', 'nropase_imprimir', 'home', 'f', 17);
INSERT INTO "public"."modulo" VALUES (42, '', 'Consultar', 'usuarioCondominio_query', 'home', 'f', 18);
INSERT INTO "public"."modulo" VALUES (43, '/usuarioCondominio_insert', 'Adicionar', 'usuarioCondominio_insert', 'home', 'f', 18);
INSERT INTO "public"."modulo" VALUES (44, '/usuarioCondominio_update', 'Actualizar', 'usuarioCondominio_update', 'home', 'f', 18);
INSERT INTO "public"."modulo" VALUES (45, '/usuarioCondominio_delete', 'Dar de Baja', 'usuarioCondominio_delete', 'home', 'f', 18);
INSERT INTO "public"."modulo" VALUES (46, '/usuarioCondominio_imprimir', 'Reportes', 'usuarioCondominio_imprimir', 'home', 'f', 18);
INSERT INTO "public"."modulo" VALUES (47, '', 'Consultar', 'areasocial_query', 'home', 'f', 19);
INSERT INTO "public"."modulo" VALUES (48, '/areasocial_insert', 'Adicionar', 'areasocial_insert', 'home', 'f', 19);
INSERT INTO "public"."modulo" VALUES (49, '/areasocial_update', 'Actualizar', 'areasocial_update', 'home', 'f', 19);
INSERT INTO "public"."modulo" VALUES (50, '/areasocial_delete', 'Dar de Baja', 'areasocial_delete', 'home', 'f', 19);
INSERT INTO "public"."modulo" VALUES (51, '/areasocial_imprimir', 'Reportes', 'areasocial_imprimir', 'home', 'f', 19);
INSERT INTO "public"."modulo" VALUES (52, '/areasocial_filtrar', 'Filtrar', 'areasocial_filtrar', 'home', 'f', 19);
INSERT INTO "public"."modulo" VALUES (53, '', 'Consultar', 'domicilio_query', 'home', 'f', 20);
INSERT INTO "public"."modulo" VALUES (54, '/domicilio_insert', 'Adicionar', 'domicilio_insert', 'home', 'f', 20);
INSERT INTO "public"."modulo" VALUES (55, '/domicilio_update', 'Actualizar', 'domicilio_update', 'home', 'f', 20);
INSERT INTO "public"."modulo" VALUES (56, '/domicilio_delete', 'Dar de Baja', 'domicilio_delete', 'home', 'f', 20);
INSERT INTO "public"."modulo" VALUES (57, '/domicilio_imprimir', 'Reportes', 'domicilio_imprimir', 'home', 'f', 20);
INSERT INTO "public"."modulo" VALUES (58, '/domicilio_filtrar', 'Filtrar', 'domicilio_filtrar', 'home', 'f', 20);
INSERT INTO "public"."modulo" VALUES (59, '/marca', 'Marcas', 'marca', 'directions_car', 't', 21);
INSERT INTO "public"."modulo" VALUES (60, '/modelo', 'Modelos', 'modelo', 'directions_car', 't', 21);
INSERT INTO "public"."modulo" VALUES (61, '/vehiculo', 'Vehiculos', 'vehiculo', 'directions_car', 't', 21);
INSERT INTO "public"."modulo" VALUES (62, '', 'Consultar', 'provper_query', 'home', 'f', 22);
INSERT INTO "public"."modulo" VALUES (63, '/provper_insert', 'Adicionar', 'provper_insert', 'home', 'f', 22);
INSERT INTO "public"."modulo" VALUES (64, '/provper_update', 'Actualizar', 'provper_update', 'home', 'f', 22);
INSERT INTO "public"."modulo" VALUES (65, '/provper_delete', 'Dar de Baja', 'provper_delete', 'home', 'f', 22);
INSERT INTO "public"."modulo" VALUES (66, '/provper_imprimir', 'Reportes', 'provper_imprimir', 'home', 'f', 22);
INSERT INTO "public"."modulo" VALUES (67, '', 'Consultar', 'residente_query', 'home', 'f', 23);
INSERT INTO "public"."modulo" VALUES (68, '/residente_insert', 'Adicionar', 'residente_insert', 'home', 'f', 23);
INSERT INTO "public"."modulo" VALUES (69, '/residente_update', 'Actualizar', 'residente_update', 'home', 'f', 23);
INSERT INTO "public"."modulo" VALUES (70, '/residente_delete', 'Dar de Baja', 'residente_delete', 'home', 'f', 23);
INSERT INTO "public"."modulo" VALUES (71, '/residente_imprimir', 'Reportes', 'residente_imprimir', 'home', 'f', 23);
INSERT INTO "public"."modulo" VALUES (72, '', 'Consultar', 'evento_query', 'home', 'f', 24);
INSERT INTO "public"."modulo" VALUES (73, '/evento_insert', 'Adicionar', 'evento_insert', 'home', 'f', 24);
INSERT INTO "public"."modulo" VALUES (74, '/evento_update', 'Actualizar', 'evento_update', 'home', 'f', 24);
INSERT INTO "public"."modulo" VALUES (75, '/evento_delete', 'Dar de Baja', 'evento_delete', 'home', 'f', 24);
INSERT INTO "public"."modulo" VALUES (76, '/evento_imprimir', 'Reportes', 'evento_imprimir', 'home', 'f', 24);
INSERT INTO "public"."modulo" VALUES (77, '', 'Consultar', 'invitado_query', 'home', 'f', 25);
INSERT INTO "public"."modulo" VALUES (78, '/invitado_insert', 'Adicionar', 'invitado_insert', 'home', 'f', 25);
INSERT INTO "public"."modulo" VALUES (79, '/invitado_update', 'Actualizar', 'invitado_update', 'home', 'f', 25);
INSERT INTO "public"."modulo" VALUES (80, '/invitado_delete', 'Dar de Baja', 'invitado_delete', 'home', 'f', 25);
INSERT INTO "public"."modulo" VALUES (81, '/invitado_imprimir', 'Reportes', 'invitado_imprimir', 'home', 'f', 25);
INSERT INTO "public"."modulo" VALUES (82, '', 'Consultar', 'movimiento_query', 'home', 'f', 26);
INSERT INTO "public"."modulo" VALUES (83, '/movimiento_insert', 'Adicionar', 'movimiento_insert', 'home', 'f', 26);
INSERT INTO "public"."modulo" VALUES (84, '/movimiento_update', 'Actualizar', 'movimiento_update', 'home', 'f', 26);
INSERT INTO "public"."modulo" VALUES (85, '/movimiento_delete', 'Dar de Baja', 'movimiento_delete', 'home', 'f', 26);
INSERT INTO "public"."modulo" VALUES (86, '/movimiento_imprimir', 'Reportes', 'movimiento_imprimir', 'home', 'f', 26);
INSERT INTO "public"."modulo" VALUES (87, '', 'Consultar', 'movimiento_p_query', 'home', 'f', 27);
INSERT INTO "public"."modulo" VALUES (88, '/movimiento_p_insert', 'Adicionar', 'movimiento_p_insert', 'home', 'f', 27);
INSERT INTO "public"."modulo" VALUES (89, '/movimiento_p_update', 'Actualizar', 'movimiento_p_update', 'home', 'f', 27);
INSERT INTO "public"."modulo" VALUES (90, '/movimiento_p_delete', 'Dar de Baja', 'movimiento_p_delete', 'home', 'f', 27);
INSERT INTO "public"."modulo" VALUES (91, '/movimiento_p_imprimir', 'Reportes', 'movimiento_p_imprimir', 'home', 'f', 27);
INSERT INTO "public"."modulo" VALUES (92, '', 'Consultar', 'portero_virtual_query', 'home', 'f', 28);
INSERT INTO "public"."modulo" VALUES (93, '/portero_virtual_insert', 'Adicionar', 'portero_virtual_insert', 'home', 'f', 28);
INSERT INTO "public"."modulo" VALUES (94, '/portero_virtual_update', 'Actualizar', 'portero_virtual_update', 'home', 'f', 28);
INSERT INTO "public"."modulo" VALUES (95, '/portero_virtual_delete', 'Dar de Baja', 'portero_virtual_delete', 'home', 'f', 28);
INSERT INTO "public"."modulo" VALUES (96, '/portero_virtual_imprimir', 'Reportes', 'portero_virtual_imprimir', 'home', 'f', 28);
INSERT INTO "public"."modulo" VALUES (97, '', 'Consultar', 'reporte_query', 'home', 'f', 29);
INSERT INTO "public"."modulo" VALUES (98, '/reporte_imprimir', 'Imprimir', 'reporte_imprimir', 'home', 'f', 29);
INSERT INTO "public"."modulo" VALUES (99, '', 'Consultar', 'registros_c_query', 'home', 'f', 30);
INSERT INTO "public"."modulo" VALUES (100, '/registros_c_imprimir', 'Imprimir', 'registros_c_imprimir', 'home', 'f', 30);
INSERT INTO "public"."modulo" VALUES (101, '', 'Consultar', 'marca_query', 'home', 'f', 59);
INSERT INTO "public"."modulo" VALUES (102, '/marca_insert', 'Adicionar', 'marca_insert', 'home', 'f', 59);
INSERT INTO "public"."modulo" VALUES (103, '/marca_update', 'Actualizar', 'marca_update', 'home', 'f', 59);
INSERT INTO "public"."modulo" VALUES (104, '/marca_delete', 'Dar de Baja', 'marca_delete', 'home', 'f', 59);
INSERT INTO "public"."modulo" VALUES (105, '/marca_imprimir', 'Reportes', 'marca_imprimir', 'home', 'f', 59);
INSERT INTO "public"."modulo" VALUES (106, '', 'Consultar', 'modelo_query', 'home', 'f', 60);
INSERT INTO "public"."modulo" VALUES (107, '/modelo_insert', 'Adicionar', 'modelo_insert', 'home', 'f', 60);
INSERT INTO "public"."modulo" VALUES (108, '/modelo_update', 'Actualizar', 'modelo_update', 'home', 'f', 60);
INSERT INTO "public"."modulo" VALUES (109, '/modelo_delete', 'Dar de Baja', 'modelo_delete', 'home', 'f', 60);
INSERT INTO "public"."modulo" VALUES (110, '/modelo_imprimir', 'Reportes', 'modelo_imprimir', 'home', 'f', 60);
INSERT INTO "public"."modulo" VALUES (111, '', 'Consultar', 'vehiculo_query', 'home', 'f', 61);
INSERT INTO "public"."modulo" VALUES (112, '/vehiculo_insert', 'Adicionar', 'vehiculo_insert', 'home', 'f', 61);
INSERT INTO "public"."modulo" VALUES (113, '/vehiculo_update', 'Actualizar', 'vehiculo_update', 'home', 'f', 61);
INSERT INTO "public"."modulo" VALUES (114, '/vehiculo_delete', 'Dar de Baja', 'vehiculo_delete', 'home', 'f', 61);
INSERT INTO "public"."modulo" VALUES (115, '/vehiculo_imprimir', 'Reportes', 'vehiculo_imprimir', 'home', 'f', 61);
INSERT INTO "public"."modulo" VALUES (116, NULL, 'Gestion de Dispositivos', 'dispositivos', 'devices_other', 't', NULL);
INSERT INTO "public"."modulo" VALUES (117, '/dispositivo', 'Dispositivos', 'dispositivo', 'devices', 't', 116);
INSERT INTO "public"."modulo" VALUES (118, '/config_acceso', 'Configuracion de Acceso', 'config_acceso', 'settings_applications', 't', 116);
INSERT INTO "public"."modulo" VALUES (119, '/registros', 'Monitor de eventos', 'registros', 'assignment', 't', 116);
INSERT INTO "public"."modulo" VALUES (120, '', 'Consultar', 'dispositivo_query', 'home', 'f', 117);
INSERT INTO "public"."modulo" VALUES (121, '/dispositivo_insert', 'Adicionar', 'dispositivo_insert', 'home', 'f', 117);
INSERT INTO "public"."modulo" VALUES (122, '/dispositivo_update', 'Actualizar', 'dispositivo_update', 'home', 'f', 117);
INSERT INTO "public"."modulo" VALUES (123, '/dispositivo_delete', 'Dar de Baja', 'dispositivo_delete', 'home', 'f', 117);
INSERT INTO "public"."modulo" VALUES (124, '', 'Consultar', 'config_acceso_query', 'home', 'f', 118);
INSERT INTO "public"."modulo" VALUES (125, '/config_acceso_insert', 'Adicionar', 'config_acceso_insert', 'home', 'f', 118);
INSERT INTO "public"."modulo" VALUES (126, '/config_acceso_update', 'Actualizar', 'config_acceso_update', 'home', 'f', 118);
INSERT INTO "public"."modulo" VALUES (127, '/config_acceso_delete', 'Dar de Baja', 'config_acceso_delete', 'home', 'f', 118);
INSERT INTO "public"."modulo" VALUES (128, '', 'Consultar', 'registros_query', 'home', 'f', 119);
INSERT INTO "public"."modulo" VALUES (129, '/registros_imprimir', 'Imprimir', 'registros_imprimir', 'home', 'f', 119);


-- ----------------------------
-- Records of acceso
-- ----------------------------
INSERT INTO "public"."acceso" VALUES (1, 2, 1);
INSERT INTO "public"."acceso" VALUES (2, 2, 3);
INSERT INTO "public"."acceso" VALUES (3, 2, 4);
INSERT INTO "public"."acceso" VALUES (4, 2, 5);
INSERT INTO "public"."acceso" VALUES (5, 2, 6);
INSERT INTO "public"."acceso" VALUES (6, 2, 7);
INSERT INTO "public"."acceso" VALUES (7, 2, 8);
INSERT INTO "public"."acceso" VALUES (8, 2, 9);
INSERT INTO "public"."acceso" VALUES (9, 2, 14);
INSERT INTO "public"."acceso" VALUES (10, 1, 1);
INSERT INTO "public"."acceso" VALUES (11, 1, 2);
INSERT INTO "public"."acceso" VALUES (12, 1, 3);
INSERT INTO "public"."acceso" VALUES (13, 1, 4);
INSERT INTO "public"."acceso" VALUES (14, 1, 5);
INSERT INTO "public"."acceso" VALUES (15, 1, 6);
INSERT INTO "public"."acceso" VALUES (16, 1, 7);
INSERT INTO "public"."acceso" VALUES (17, 1, 8);
INSERT INTO "public"."acceso" VALUES (18, 1, 9);
INSERT INTO "public"."acceso" VALUES (19, 1, 10);
INSERT INTO "public"."acceso" VALUES (20, 1, 11);
INSERT INTO "public"."acceso" VALUES (21, 1, 12);
INSERT INTO "public"."acceso" VALUES (22, 1, 13);
INSERT INTO "public"."acceso" VALUES (23, 1, 14);
INSERT INTO "public"."acceso" VALUES (24, 6, 26);
INSERT INTO "public"."acceso" VALUES (25, 6, 27);
INSERT INTO "public"."acceso" VALUES (26, 6, 30);
INSERT INTO "public"."acceso" VALUES (27, 6, 82);
INSERT INTO "public"."acceso" VALUES (28, 6, 83);
INSERT INTO "public"."acceso" VALUES (29, 6, 84);
INSERT INTO "public"."acceso" VALUES (30, 6, 87);
INSERT INTO "public"."acceso" VALUES (31, 6, 88);
INSERT INTO "public"."acceso" VALUES (32, 6, 89);
INSERT INTO "public"."acceso" VALUES (33, 6, 99);
INSERT INTO "public"."acceso" VALUES (34, 6, 100);
INSERT INTO "public"."acceso" VALUES (35, 3, 15);
INSERT INTO "public"."acceso" VALUES (36, 3, 16);
INSERT INTO "public"."acceso" VALUES (37, 3, 17);
INSERT INTO "public"."acceso" VALUES (38, 3, 18);
INSERT INTO "public"."acceso" VALUES (39, 3, 19);
INSERT INTO "public"."acceso" VALUES (40, 3, 20);
INSERT INTO "public"."acceso" VALUES (41, 3, 21);
INSERT INTO "public"."acceso" VALUES (42, 3, 59);
INSERT INTO "public"."acceso" VALUES (43, 3, 60);
INSERT INTO "public"."acceso" VALUES (44, 3, 61);
INSERT INTO "public"."acceso" VALUES (45, 3, 22);
INSERT INTO "public"."acceso" VALUES (46, 3, 23);
INSERT INTO "public"."acceso" VALUES (47, 3, 24);
INSERT INTO "public"."acceso" VALUES (48, 3, 25);
INSERT INTO "public"."acceso" VALUES (49, 3, 26);
INSERT INTO "public"."acceso" VALUES (50, 3, 27);
INSERT INTO "public"."acceso" VALUES (51, 3, 28);
INSERT INTO "public"."acceso" VALUES (52, 3, 29);
INSERT INTO "public"."acceso" VALUES (53, 3, 30);
INSERT INTO "public"."acceso" VALUES (54, 3, 31);
INSERT INTO "public"."acceso" VALUES (55, 3, 32);
INSERT INTO "public"."acceso" VALUES (56, 3, 33);
INSERT INTO "public"."acceso" VALUES (57, 3, 34);
INSERT INTO "public"."acceso" VALUES (58, 3, 35);
INSERT INTO "public"."acceso" VALUES (59, 3, 36);
INSERT INTO "public"."acceso" VALUES (60, 3, 37);
INSERT INTO "public"."acceso" VALUES (61, 3, 38);
INSERT INTO "public"."acceso" VALUES (62, 3, 39);
INSERT INTO "public"."acceso" VALUES (63, 3, 41);
INSERT INTO "public"."acceso" VALUES (64, 3, 42);
INSERT INTO "public"."acceso" VALUES (65, 3, 43);
INSERT INTO "public"."acceso" VALUES (66, 3, 44);
INSERT INTO "public"."acceso" VALUES (67, 3, 45);
INSERT INTO "public"."acceso" VALUES (68, 3, 46);
INSERT INTO "public"."acceso" VALUES (69, 3, 47);
INSERT INTO "public"."acceso" VALUES (70, 3, 48);
INSERT INTO "public"."acceso" VALUES (71, 3, 49);
INSERT INTO "public"."acceso" VALUES (72, 3, 50);
INSERT INTO "public"."acceso" VALUES (73, 3, 51);
INSERT INTO "public"."acceso" VALUES (74, 3, 52);
INSERT INTO "public"."acceso" VALUES (75, 3, 53);
INSERT INTO "public"."acceso" VALUES (76, 3, 54);
INSERT INTO "public"."acceso" VALUES (77, 3, 55);
INSERT INTO "public"."acceso" VALUES (78, 3, 56);
INSERT INTO "public"."acceso" VALUES (79, 3, 57);
INSERT INTO "public"."acceso" VALUES (80, 3, 67);
INSERT INTO "public"."acceso" VALUES (81, 3, 68);
INSERT INTO "public"."acceso" VALUES (82, 3, 69);
INSERT INTO "public"."acceso" VALUES (83, 3, 70);
INSERT INTO "public"."acceso" VALUES (84, 3, 71);
INSERT INTO "public"."acceso" VALUES (85, 3, 62);
INSERT INTO "public"."acceso" VALUES (86, 3, 63);
INSERT INTO "public"."acceso" VALUES (87, 3, 64);
INSERT INTO "public"."acceso" VALUES (88, 3, 65);
INSERT INTO "public"."acceso" VALUES (89, 3, 66);
INSERT INTO "public"."acceso" VALUES (90, 3, 101);
INSERT INTO "public"."acceso" VALUES (91, 3, 102);
INSERT INTO "public"."acceso" VALUES (92, 3, 103);
INSERT INTO "public"."acceso" VALUES (93, 3, 104);
INSERT INTO "public"."acceso" VALUES (94, 3, 105);
INSERT INTO "public"."acceso" VALUES (95, 3, 106);
INSERT INTO "public"."acceso" VALUES (96, 3, 107);
INSERT INTO "public"."acceso" VALUES (97, 3, 108);
INSERT INTO "public"."acceso" VALUES (98, 3, 109);
INSERT INTO "public"."acceso" VALUES (99, 3, 110);
INSERT INTO "public"."acceso" VALUES (100, 3, 111);
INSERT INTO "public"."acceso" VALUES (101, 3, 112);
INSERT INTO "public"."acceso" VALUES (102, 3, 113);
INSERT INTO "public"."acceso" VALUES (103, 3, 114);
INSERT INTO "public"."acceso" VALUES (104, 3, 115);
INSERT INTO "public"."acceso" VALUES (105, 3, 72);
INSERT INTO "public"."acceso" VALUES (106, 3, 73);
INSERT INTO "public"."acceso" VALUES (107, 3, 74);
INSERT INTO "public"."acceso" VALUES (108, 3, 75);
INSERT INTO "public"."acceso" VALUES (109, 3, 76);
INSERT INTO "public"."acceso" VALUES (110, 3, 77);
INSERT INTO "public"."acceso" VALUES (111, 3, 78);
INSERT INTO "public"."acceso" VALUES (112, 3, 79);
INSERT INTO "public"."acceso" VALUES (113, 3, 80);
INSERT INTO "public"."acceso" VALUES (114, 3, 81);
INSERT INTO "public"."acceso" VALUES (115, 3, 82);
INSERT INTO "public"."acceso" VALUES (116, 3, 83);
INSERT INTO "public"."acceso" VALUES (117, 3, 84);
INSERT INTO "public"."acceso" VALUES (118, 3, 85);
INSERT INTO "public"."acceso" VALUES (119, 3, 86);
INSERT INTO "public"."acceso" VALUES (120, 3, 87);
INSERT INTO "public"."acceso" VALUES (121, 3, 88);
INSERT INTO "public"."acceso" VALUES (122, 3, 89);
INSERT INTO "public"."acceso" VALUES (123, 3, 90);
INSERT INTO "public"."acceso" VALUES (124, 3, 91);
INSERT INTO "public"."acceso" VALUES (125, 3, 92);
INSERT INTO "public"."acceso" VALUES (126, 3, 93);
INSERT INTO "public"."acceso" VALUES (127, 3, 94);
INSERT INTO "public"."acceso" VALUES (128, 3, 95);
INSERT INTO "public"."acceso" VALUES (129, 3, 96);
INSERT INTO "public"."acceso" VALUES (130, 3, 97);
INSERT INTO "public"."acceso" VALUES (131, 3, 98);
INSERT INTO "public"."acceso" VALUES (132, 3, 99);
INSERT INTO "public"."acceso" VALUES (133, 3, 100);
INSERT INTO "public"."acceso" VALUES (134, 5, 15);
INSERT INTO "public"."acceso" VALUES (135, 5, 16);
INSERT INTO "public"."acceso" VALUES (136, 5, 17);
INSERT INTO "public"."acceso" VALUES (137, 5, 18);
INSERT INTO "public"."acceso" VALUES (138, 5, 19);
INSERT INTO "public"."acceso" VALUES (139, 5, 20);
INSERT INTO "public"."acceso" VALUES (140, 5, 21);
INSERT INTO "public"."acceso" VALUES (141, 5, 59);
INSERT INTO "public"."acceso" VALUES (142, 5, 60);
INSERT INTO "public"."acceso" VALUES (143, 5, 61);
INSERT INTO "public"."acceso" VALUES (144, 5, 22);
INSERT INTO "public"."acceso" VALUES (145, 5, 23);
INSERT INTO "public"."acceso" VALUES (146, 5, 24);
INSERT INTO "public"."acceso" VALUES (147, 5, 25);
INSERT INTO "public"."acceso" VALUES (148, 5, 26);
INSERT INTO "public"."acceso" VALUES (149, 5, 27);
INSERT INTO "public"."acceso" VALUES (150, 5, 28);
INSERT INTO "public"."acceso" VALUES (151, 5, 29);
INSERT INTO "public"."acceso" VALUES (152, 5, 30);
INSERT INTO "public"."acceso" VALUES (153, 5, 31);
INSERT INTO "public"."acceso" VALUES (154, 5, 32);
INSERT INTO "public"."acceso" VALUES (155, 5, 33);
INSERT INTO "public"."acceso" VALUES (156, 5, 34);
INSERT INTO "public"."acceso" VALUES (157, 5, 35);
INSERT INTO "public"."acceso" VALUES (158, 5, 36);
INSERT INTO "public"."acceso" VALUES (159, 5, 37);
INSERT INTO "public"."acceso" VALUES (160, 5, 38);
INSERT INTO "public"."acceso" VALUES (161, 5, 39);
INSERT INTO "public"."acceso" VALUES (162, 5, 41);
INSERT INTO "public"."acceso" VALUES (163, 5, 42);
INSERT INTO "public"."acceso" VALUES (164, 5, 43);
INSERT INTO "public"."acceso" VALUES (165, 5, 44);
INSERT INTO "public"."acceso" VALUES (166, 5, 45);
INSERT INTO "public"."acceso" VALUES (167, 5, 46);
INSERT INTO "public"."acceso" VALUES (168, 5, 47);
INSERT INTO "public"."acceso" VALUES (169, 5, 48);
INSERT INTO "public"."acceso" VALUES (170, 5, 49);
INSERT INTO "public"."acceso" VALUES (171, 5, 50);
INSERT INTO "public"."acceso" VALUES (172, 5, 51);
INSERT INTO "public"."acceso" VALUES (173, 5, 52);
INSERT INTO "public"."acceso" VALUES (174, 5, 53);
INSERT INTO "public"."acceso" VALUES (175, 5, 54);
INSERT INTO "public"."acceso" VALUES (176, 5, 55);
INSERT INTO "public"."acceso" VALUES (177, 5, 56);
INSERT INTO "public"."acceso" VALUES (178, 5, 57);
INSERT INTO "public"."acceso" VALUES (179, 5, 67);
INSERT INTO "public"."acceso" VALUES (180, 5, 68);
INSERT INTO "public"."acceso" VALUES (181, 5, 69);
INSERT INTO "public"."acceso" VALUES (182, 5, 70);
INSERT INTO "public"."acceso" VALUES (183, 5, 71);
INSERT INTO "public"."acceso" VALUES (184, 5, 62);
INSERT INTO "public"."acceso" VALUES (185, 5, 63);
INSERT INTO "public"."acceso" VALUES (186, 5, 64);
INSERT INTO "public"."acceso" VALUES (187, 5, 65);
INSERT INTO "public"."acceso" VALUES (188, 5, 66);
INSERT INTO "public"."acceso" VALUES (189, 5, 101);
INSERT INTO "public"."acceso" VALUES (190, 5, 102);
INSERT INTO "public"."acceso" VALUES (191, 5, 103);
INSERT INTO "public"."acceso" VALUES (192, 5, 104);
INSERT INTO "public"."acceso" VALUES (193, 5, 105);
INSERT INTO "public"."acceso" VALUES (194, 5, 106);
INSERT INTO "public"."acceso" VALUES (195, 5, 107);
INSERT INTO "public"."acceso" VALUES (196, 5, 108);
INSERT INTO "public"."acceso" VALUES (197, 5, 109);
INSERT INTO "public"."acceso" VALUES (198, 5, 110);
INSERT INTO "public"."acceso" VALUES (199, 5, 111);
INSERT INTO "public"."acceso" VALUES (200, 5, 112);
INSERT INTO "public"."acceso" VALUES (201, 5, 113);
INSERT INTO "public"."acceso" VALUES (202, 5, 114);
INSERT INTO "public"."acceso" VALUES (203, 5, 115);
INSERT INTO "public"."acceso" VALUES (204, 5, 72);
INSERT INTO "public"."acceso" VALUES (205, 5, 73);
INSERT INTO "public"."acceso" VALUES (206, 5, 74);
INSERT INTO "public"."acceso" VALUES (207, 5, 75);
INSERT INTO "public"."acceso" VALUES (208, 5, 76);
INSERT INTO "public"."acceso" VALUES (209, 5, 77);
INSERT INTO "public"."acceso" VALUES (210, 5, 78);
INSERT INTO "public"."acceso" VALUES (211, 5, 79);
INSERT INTO "public"."acceso" VALUES (212, 5, 80);
INSERT INTO "public"."acceso" VALUES (213, 5, 81);
INSERT INTO "public"."acceso" VALUES (214, 5, 82);
INSERT INTO "public"."acceso" VALUES (215, 5, 83);
INSERT INTO "public"."acceso" VALUES (216, 5, 84);
INSERT INTO "public"."acceso" VALUES (217, 5, 85);
INSERT INTO "public"."acceso" VALUES (218, 5, 86);
INSERT INTO "public"."acceso" VALUES (219, 5, 87);
INSERT INTO "public"."acceso" VALUES (220, 5, 88);
INSERT INTO "public"."acceso" VALUES (221, 5, 89);
INSERT INTO "public"."acceso" VALUES (222, 5, 90);
INSERT INTO "public"."acceso" VALUES (223, 5, 91);
INSERT INTO "public"."acceso" VALUES (224, 5, 92);
INSERT INTO "public"."acceso" VALUES (225, 5, 93);
INSERT INTO "public"."acceso" VALUES (226, 5, 94);
INSERT INTO "public"."acceso" VALUES (227, 5, 95);
INSERT INTO "public"."acceso" VALUES (228, 5, 96);
INSERT INTO "public"."acceso" VALUES (229, 5, 97);
INSERT INTO "public"."acceso" VALUES (230, 5, 98);
INSERT INTO "public"."acceso" VALUES (231, 5, 99);
INSERT INTO "public"."acceso" VALUES (232, 5, 100);
INSERT INTO "public"."acceso" VALUES (233, 4, 15);
INSERT INTO "public"."acceso" VALUES (234, 4, 17);
INSERT INTO "public"."acceso" VALUES (235, 4, 19);
INSERT INTO "public"."acceso" VALUES (236, 4, 20);
INSERT INTO "public"."acceso" VALUES (237, 4, 21);
INSERT INTO "public"."acceso" VALUES (238, 4, 59);
INSERT INTO "public"."acceso" VALUES (239, 4, 60);
INSERT INTO "public"."acceso" VALUES (240, 4, 61);
INSERT INTO "public"."acceso" VALUES (241, 4, 22);
INSERT INTO "public"."acceso" VALUES (242, 4, 23);
INSERT INTO "public"."acceso" VALUES (243, 4, 36);
INSERT INTO "public"."acceso" VALUES (244, 4, 37);
INSERT INTO "public"."acceso" VALUES (245, 4, 38);
INSERT INTO "public"."acceso" VALUES (246, 4, 39);
INSERT INTO "public"."acceso" VALUES (247, 4, 41);
INSERT INTO "public"."acceso" VALUES (248, 4, 47);
INSERT INTO "public"."acceso" VALUES (249, 4, 48);
INSERT INTO "public"."acceso" VALUES (250, 4, 49);
INSERT INTO "public"."acceso" VALUES (251, 4, 50);
INSERT INTO "public"."acceso" VALUES (252, 4, 51);
INSERT INTO "public"."acceso" VALUES (253, 4, 52);
INSERT INTO "public"."acceso" VALUES (254, 4, 53);
INSERT INTO "public"."acceso" VALUES (255, 4, 54);
INSERT INTO "public"."acceso" VALUES (256, 4, 55);
INSERT INTO "public"."acceso" VALUES (257, 4, 56);
INSERT INTO "public"."acceso" VALUES (258, 4, 57);
INSERT INTO "public"."acceso" VALUES (259, 4, 58);
INSERT INTO "public"."acceso" VALUES (260, 4, 67);
INSERT INTO "public"."acceso" VALUES (261, 4, 68);
INSERT INTO "public"."acceso" VALUES (262, 4, 69);
INSERT INTO "public"."acceso" VALUES (263, 4, 70);
INSERT INTO "public"."acceso" VALUES (264, 4, 71);
INSERT INTO "public"."acceso" VALUES (265, 4, 62);
INSERT INTO "public"."acceso" VALUES (266, 4, 63);
INSERT INTO "public"."acceso" VALUES (267, 4, 64);
INSERT INTO "public"."acceso" VALUES (268, 4, 65);
INSERT INTO "public"."acceso" VALUES (269, 4, 66);
INSERT INTO "public"."acceso" VALUES (270, 4, 101);
INSERT INTO "public"."acceso" VALUES (271, 4, 102);
INSERT INTO "public"."acceso" VALUES (272, 4, 103);
INSERT INTO "public"."acceso" VALUES (273, 4, 104);
INSERT INTO "public"."acceso" VALUES (274, 4, 105);
INSERT INTO "public"."acceso" VALUES (275, 4, 106);
INSERT INTO "public"."acceso" VALUES (276, 4, 107);
INSERT INTO "public"."acceso" VALUES (277, 4, 108);
INSERT INTO "public"."acceso" VALUES (278, 4, 109);
INSERT INTO "public"."acceso" VALUES (279, 4, 110);
INSERT INTO "public"."acceso" VALUES (280, 4, 111);
INSERT INTO "public"."acceso" VALUES (281, 4, 112);
INSERT INTO "public"."acceso" VALUES (282, 4, 113);
INSERT INTO "public"."acceso" VALUES (283, 4, 114);
INSERT INTO "public"."acceso" VALUES (284, 4, 115);
INSERT INTO "public"."acceso" VALUES (285, 1, 15);
INSERT INTO "public"."acceso" VALUES (286, 1, 16);
INSERT INTO "public"."acceso" VALUES (287, 1, 17);
INSERT INTO "public"."acceso" VALUES (288, 1, 18);
INSERT INTO "public"."acceso" VALUES (289, 1, 19);
INSERT INTO "public"."acceso" VALUES (290, 1, 20);
INSERT INTO "public"."acceso" VALUES (291, 1, 21);
INSERT INTO "public"."acceso" VALUES (292, 1, 59);
INSERT INTO "public"."acceso" VALUES (293, 1, 60);
INSERT INTO "public"."acceso" VALUES (294, 1, 61);
INSERT INTO "public"."acceso" VALUES (295, 1, 22);
INSERT INTO "public"."acceso" VALUES (296, 1, 23);
INSERT INTO "public"."acceso" VALUES (297, 1, 24);
INSERT INTO "public"."acceso" VALUES (298, 1, 25);
INSERT INTO "public"."acceso" VALUES (299, 1, 26);
INSERT INTO "public"."acceso" VALUES (300, 1, 27);
INSERT INTO "public"."acceso" VALUES (301, 1, 28);
INSERT INTO "public"."acceso" VALUES (302, 1, 29);
INSERT INTO "public"."acceso" VALUES (303, 1, 30);
INSERT INTO "public"."acceso" VALUES (304, 1, 31);
INSERT INTO "public"."acceso" VALUES (305, 1, 32);
INSERT INTO "public"."acceso" VALUES (306, 1, 33);
INSERT INTO "public"."acceso" VALUES (307, 1, 34);
INSERT INTO "public"."acceso" VALUES (308, 1, 35);
INSERT INTO "public"."acceso" VALUES (309, 1, 36);
INSERT INTO "public"."acceso" VALUES (310, 1, 37);
INSERT INTO "public"."acceso" VALUES (311, 1, 38);
INSERT INTO "public"."acceso" VALUES (312, 1, 39);
INSERT INTO "public"."acceso" VALUES (313, 1, 41);
INSERT INTO "public"."acceso" VALUES (314, 1, 42);
INSERT INTO "public"."acceso" VALUES (315, 1, 43);
INSERT INTO "public"."acceso" VALUES (316, 1, 44);
INSERT INTO "public"."acceso" VALUES (317, 1, 45);
INSERT INTO "public"."acceso" VALUES (318, 1, 46);
INSERT INTO "public"."acceso" VALUES (319, 1, 47);
INSERT INTO "public"."acceso" VALUES (320, 1, 48);
INSERT INTO "public"."acceso" VALUES (321, 1, 49);
INSERT INTO "public"."acceso" VALUES (322, 1, 50);
INSERT INTO "public"."acceso" VALUES (323, 1, 51);
INSERT INTO "public"."acceso" VALUES (324, 1, 52);
INSERT INTO "public"."acceso" VALUES (325, 1, 53);
INSERT INTO "public"."acceso" VALUES (326, 1, 54);
INSERT INTO "public"."acceso" VALUES (327, 1, 55);
INSERT INTO "public"."acceso" VALUES (328, 1, 56);
INSERT INTO "public"."acceso" VALUES (329, 1, 57);
INSERT INTO "public"."acceso" VALUES (330, 1, 58);
INSERT INTO "public"."acceso" VALUES (331, 1, 67);
INSERT INTO "public"."acceso" VALUES (332, 1, 68);
INSERT INTO "public"."acceso" VALUES (333, 1, 69);
INSERT INTO "public"."acceso" VALUES (334, 1, 70);
INSERT INTO "public"."acceso" VALUES (335, 1, 71);
INSERT INTO "public"."acceso" VALUES (336, 1, 62);
INSERT INTO "public"."acceso" VALUES (337, 1, 63);
INSERT INTO "public"."acceso" VALUES (338, 1, 64);
INSERT INTO "public"."acceso" VALUES (339, 1, 65);
INSERT INTO "public"."acceso" VALUES (340, 1, 66);
INSERT INTO "public"."acceso" VALUES (341, 1, 101);
INSERT INTO "public"."acceso" VALUES (342, 1, 102);
INSERT INTO "public"."acceso" VALUES (343, 1, 103);
INSERT INTO "public"."acceso" VALUES (344, 1, 104);
INSERT INTO "public"."acceso" VALUES (345, 1, 105);
INSERT INTO "public"."acceso" VALUES (346, 1, 106);
INSERT INTO "public"."acceso" VALUES (347, 1, 107);
INSERT INTO "public"."acceso" VALUES (348, 1, 108);
INSERT INTO "public"."acceso" VALUES (349, 1, 109);
INSERT INTO "public"."acceso" VALUES (350, 1, 110);
INSERT INTO "public"."acceso" VALUES (351, 1, 111);
INSERT INTO "public"."acceso" VALUES (352, 1, 112);
INSERT INTO "public"."acceso" VALUES (353, 1, 113);
INSERT INTO "public"."acceso" VALUES (354, 1, 114);
INSERT INTO "public"."acceso" VALUES (355, 1, 115);
INSERT INTO "public"."acceso" VALUES (356, 1, 72);
INSERT INTO "public"."acceso" VALUES (357, 1, 73);
INSERT INTO "public"."acceso" VALUES (358, 1, 74);
INSERT INTO "public"."acceso" VALUES (359, 1, 75);
INSERT INTO "public"."acceso" VALUES (360, 1, 76);
INSERT INTO "public"."acceso" VALUES (361, 1, 77);
INSERT INTO "public"."acceso" VALUES (362, 1, 78);
INSERT INTO "public"."acceso" VALUES (363, 1, 79);
INSERT INTO "public"."acceso" VALUES (364, 1, 80);
INSERT INTO "public"."acceso" VALUES (365, 1, 81);
INSERT INTO "public"."acceso" VALUES (366, 1, 82);
INSERT INTO "public"."acceso" VALUES (367, 1, 83);
INSERT INTO "public"."acceso" VALUES (368, 1, 84);
INSERT INTO "public"."acceso" VALUES (369, 1, 85);
INSERT INTO "public"."acceso" VALUES (370, 1, 86);
INSERT INTO "public"."acceso" VALUES (371, 1, 87);
INSERT INTO "public"."acceso" VALUES (372, 1, 88);
INSERT INTO "public"."acceso" VALUES (373, 1, 89);
INSERT INTO "public"."acceso" VALUES (374, 1, 90);
INSERT INTO "public"."acceso" VALUES (375, 1, 91);
INSERT INTO "public"."acceso" VALUES (376, 1, 92);
INSERT INTO "public"."acceso" VALUES (377, 1, 93);
INSERT INTO "public"."acceso" VALUES (378, 1, 94);
INSERT INTO "public"."acceso" VALUES (379, 1, 95);
INSERT INTO "public"."acceso" VALUES (380, 1, 96);
INSERT INTO "public"."acceso" VALUES (381, 1, 97);
INSERT INTO "public"."acceso" VALUES (382, 1, 98);
INSERT INTO "public"."acceso" VALUES (383, 1, 99);
INSERT INTO "public"."acceso" VALUES (384, 1, 100);
INSERT INTO "public"."acceso" VALUES (385, 7, 24);
INSERT INTO "public"."acceso" VALUES (386, 7, 25);
INSERT INTO "public"."acceso" VALUES (387, 7, 72);
INSERT INTO "public"."acceso" VALUES (388, 7, 73);
INSERT INTO "public"."acceso" VALUES (389, 7, 74);
INSERT INTO "public"."acceso" VALUES (390, 7, 75);
INSERT INTO "public"."acceso" VALUES (391, 7, 76);
INSERT INTO "public"."acceso" VALUES (392, 7, 77);
INSERT INTO "public"."acceso" VALUES (393, 7, 78);
INSERT INTO "public"."acceso" VALUES (394, 7, 79);
INSERT INTO "public"."acceso" VALUES (395, 7, 80);
INSERT INTO "public"."acceso" VALUES (396, 7, 81);
INSERT INTO "public"."acceso" VALUES (397, 2, 15);
INSERT INTO "public"."acceso" VALUES (398, 2, 16);
INSERT INTO "public"."acceso" VALUES (399, 2, 17);
INSERT INTO "public"."acceso" VALUES (400, 2, 18);
INSERT INTO "public"."acceso" VALUES (401, 2, 19);
INSERT INTO "public"."acceso" VALUES (402, 2, 20);
INSERT INTO "public"."acceso" VALUES (403, 2, 21);
INSERT INTO "public"."acceso" VALUES (404, 2, 59);
INSERT INTO "public"."acceso" VALUES (405, 2, 60);
INSERT INTO "public"."acceso" VALUES (406, 2, 61);
INSERT INTO "public"."acceso" VALUES (407, 2, 22);
INSERT INTO "public"."acceso" VALUES (408, 2, 23);
INSERT INTO "public"."acceso" VALUES (409, 2, 24);
INSERT INTO "public"."acceso" VALUES (410, 2, 25);
INSERT INTO "public"."acceso" VALUES (411, 2, 26);
INSERT INTO "public"."acceso" VALUES (412, 2, 27);
INSERT INTO "public"."acceso" VALUES (413, 2, 28);
INSERT INTO "public"."acceso" VALUES (414, 2, 29);
INSERT INTO "public"."acceso" VALUES (415, 2, 30);
INSERT INTO "public"."acceso" VALUES (416, 2, 31);
INSERT INTO "public"."acceso" VALUES (417, 2, 32);
INSERT INTO "public"."acceso" VALUES (418, 2, 33);
INSERT INTO "public"."acceso" VALUES (419, 2, 34);
INSERT INTO "public"."acceso" VALUES (420, 2, 35);
INSERT INTO "public"."acceso" VALUES (421, 2, 36);
INSERT INTO "public"."acceso" VALUES (422, 2, 37);
INSERT INTO "public"."acceso" VALUES (423, 2, 38);
INSERT INTO "public"."acceso" VALUES (424, 2, 39);
INSERT INTO "public"."acceso" VALUES (425, 2, 41);
INSERT INTO "public"."acceso" VALUES (426, 2, 42);
INSERT INTO "public"."acceso" VALUES (427, 2, 43);
INSERT INTO "public"."acceso" VALUES (428, 2, 44);
INSERT INTO "public"."acceso" VALUES (429, 2, 45);
INSERT INTO "public"."acceso" VALUES (430, 2, 46);
INSERT INTO "public"."acceso" VALUES (431, 2, 47);
INSERT INTO "public"."acceso" VALUES (432, 2, 48);
INSERT INTO "public"."acceso" VALUES (433, 2, 49);
INSERT INTO "public"."acceso" VALUES (434, 2, 50);
INSERT INTO "public"."acceso" VALUES (435, 2, 51);
INSERT INTO "public"."acceso" VALUES (436, 2, 52);
INSERT INTO "public"."acceso" VALUES (437, 2, 53);
INSERT INTO "public"."acceso" VALUES (438, 2, 54);
INSERT INTO "public"."acceso" VALUES (439, 2, 55);
INSERT INTO "public"."acceso" VALUES (440, 2, 56);
INSERT INTO "public"."acceso" VALUES (441, 2, 57);
INSERT INTO "public"."acceso" VALUES (442, 2, 58);
INSERT INTO "public"."acceso" VALUES (443, 2, 67);
INSERT INTO "public"."acceso" VALUES (444, 2, 68);
INSERT INTO "public"."acceso" VALUES (445, 2, 69);
INSERT INTO "public"."acceso" VALUES (446, 2, 70);
INSERT INTO "public"."acceso" VALUES (447, 2, 71);
INSERT INTO "public"."acceso" VALUES (448, 2, 62);
INSERT INTO "public"."acceso" VALUES (449, 2, 63);
INSERT INTO "public"."acceso" VALUES (450, 2, 64);
INSERT INTO "public"."acceso" VALUES (451, 2, 65);
INSERT INTO "public"."acceso" VALUES (452, 2, 66);
INSERT INTO "public"."acceso" VALUES (453, 2, 101);
INSERT INTO "public"."acceso" VALUES (454, 2, 102);
INSERT INTO "public"."acceso" VALUES (455, 2, 103);
INSERT INTO "public"."acceso" VALUES (456, 2, 104);
INSERT INTO "public"."acceso" VALUES (457, 2, 105);
INSERT INTO "public"."acceso" VALUES (458, 2, 106);
INSERT INTO "public"."acceso" VALUES (459, 2, 107);
INSERT INTO "public"."acceso" VALUES (460, 2, 108);
INSERT INTO "public"."acceso" VALUES (461, 2, 109);
INSERT INTO "public"."acceso" VALUES (462, 2, 110);
INSERT INTO "public"."acceso" VALUES (463, 2, 111);
INSERT INTO "public"."acceso" VALUES (464, 2, 112);
INSERT INTO "public"."acceso" VALUES (465, 2, 113);
INSERT INTO "public"."acceso" VALUES (466, 2, 114);
INSERT INTO "public"."acceso" VALUES (467, 2, 115);
INSERT INTO "public"."acceso" VALUES (468, 2, 72);
INSERT INTO "public"."acceso" VALUES (469, 2, 73);
INSERT INTO "public"."acceso" VALUES (470, 2, 74);
INSERT INTO "public"."acceso" VALUES (471, 2, 75);
INSERT INTO "public"."acceso" VALUES (472, 2, 76);
INSERT INTO "public"."acceso" VALUES (473, 2, 77);
INSERT INTO "public"."acceso" VALUES (474, 2, 78);
INSERT INTO "public"."acceso" VALUES (475, 2, 79);
INSERT INTO "public"."acceso" VALUES (476, 2, 80);
INSERT INTO "public"."acceso" VALUES (477, 2, 81);
INSERT INTO "public"."acceso" VALUES (478, 2, 82);
INSERT INTO "public"."acceso" VALUES (479, 2, 83);
INSERT INTO "public"."acceso" VALUES (480, 2, 84);
INSERT INTO "public"."acceso" VALUES (481, 2, 85);
INSERT INTO "public"."acceso" VALUES (482, 2, 86);
INSERT INTO "public"."acceso" VALUES (483, 2, 87);
INSERT INTO "public"."acceso" VALUES (484, 2, 88);
INSERT INTO "public"."acceso" VALUES (485, 2, 89);
INSERT INTO "public"."acceso" VALUES (486, 2, 90);
INSERT INTO "public"."acceso" VALUES (487, 2, 91);
INSERT INTO "public"."acceso" VALUES (488, 2, 92);
INSERT INTO "public"."acceso" VALUES (489, 2, 93);
INSERT INTO "public"."acceso" VALUES (490, 2, 94);
INSERT INTO "public"."acceso" VALUES (491, 2, 95);
INSERT INTO "public"."acceso" VALUES (492, 2, 96);
INSERT INTO "public"."acceso" VALUES (493, 2, 97);
INSERT INTO "public"."acceso" VALUES (494, 2, 98);
INSERT INTO "public"."acceso" VALUES (495, 2, 99);
INSERT INTO "public"."acceso" VALUES (496, 2, 100);
INSERT INTO "public"."acceso" VALUES (497, 4, 116);
INSERT INTO "public"."acceso" VALUES (498, 4, 117);
INSERT INTO "public"."acceso" VALUES (499, 4, 118);
INSERT INTO "public"."acceso" VALUES (500, 4, 119);
INSERT INTO "public"."acceso" VALUES (501, 4, 120);
INSERT INTO "public"."acceso" VALUES (502, 4, 121);
INSERT INTO "public"."acceso" VALUES (503, 4, 122);
INSERT INTO "public"."acceso" VALUES (504, 4, 123);
INSERT INTO "public"."acceso" VALUES (505, 4, 124);
INSERT INTO "public"."acceso" VALUES (506, 4, 125);
INSERT INTO "public"."acceso" VALUES (507, 4, 126);
INSERT INTO "public"."acceso" VALUES (508, 4, 127);
INSERT INTO "public"."acceso" VALUES (509, 4, 128);
INSERT INTO "public"."acceso" VALUES (510, 4, 129);
INSERT INTO "public"."acceso" VALUES (511, 1, 116);
INSERT INTO "public"."acceso" VALUES (512, 1, 117);
INSERT INTO "public"."acceso" VALUES (513, 1, 118);
INSERT INTO "public"."acceso" VALUES (514, 1, 119);
INSERT INTO "public"."acceso" VALUES (515, 1, 120);
INSERT INTO "public"."acceso" VALUES (516, 1, 121);
INSERT INTO "public"."acceso" VALUES (517, 1, 122);
INSERT INTO "public"."acceso" VALUES (518, 1, 123);
INSERT INTO "public"."acceso" VALUES (519, 1, 124);
INSERT INTO "public"."acceso" VALUES (520, 1, 125);
INSERT INTO "public"."acceso" VALUES (521, 1, 126);
INSERT INTO "public"."acceso" VALUES (522, 1, 127);
INSERT INTO "public"."acceso" VALUES (523, 1, 128);
INSERT INTO "public"."acceso" VALUES (524, 1, 129);
INSERT INTO "public"."acceso" VALUES (525, 5, 116);
INSERT INTO "public"."acceso" VALUES (526, 5, 117);
INSERT INTO "public"."acceso" VALUES (527, 5, 118);
INSERT INTO "public"."acceso" VALUES (528, 5, 119);
INSERT INTO "public"."acceso" VALUES (529, 5, 120);
INSERT INTO "public"."acceso" VALUES (530, 5, 121);
INSERT INTO "public"."acceso" VALUES (531, 5, 122);
INSERT INTO "public"."acceso" VALUES (532, 5, 123);
INSERT INTO "public"."acceso" VALUES (533, 5, 124);
INSERT INTO "public"."acceso" VALUES (534, 5, 125);
INSERT INTO "public"."acceso" VALUES (535, 5, 126);
INSERT INTO "public"."acceso" VALUES (536, 5, 127);
INSERT INTO "public"."acceso" VALUES (537, 5, 128);
INSERT INTO "public"."acceso" VALUES (538, 5, 129);
INSERT INTO "public"."acceso" VALUES (539, 2, 116);
INSERT INTO "public"."acceso" VALUES (540, 2, 117);
INSERT INTO "public"."acceso" VALUES (541, 2, 118);
INSERT INTO "public"."acceso" VALUES (542, 2, 119);
INSERT INTO "public"."acceso" VALUES (543, 2, 120);
INSERT INTO "public"."acceso" VALUES (544, 2, 121);
INSERT INTO "public"."acceso" VALUES (545, 2, 122);
INSERT INTO "public"."acceso" VALUES (546, 2, 123);
INSERT INTO "public"."acceso" VALUES (547, 2, 124);
INSERT INTO "public"."acceso" VALUES (548, 2, 125);
INSERT INTO "public"."acceso" VALUES (549, 2, 126);
INSERT INTO "public"."acceso" VALUES (550, 2, 127);
INSERT INTO "public"."acceso" VALUES (551, 2, 128);
INSERT INTO "public"."acceso" VALUES (552, 2, 129);
INSERT INTO "public"."acceso" VALUES (553, 3, 116);
INSERT INTO "public"."acceso" VALUES (554, 3, 117);
INSERT INTO "public"."acceso" VALUES (555, 3, 118);
INSERT INTO "public"."acceso" VALUES (556, 3, 119);
INSERT INTO "public"."acceso" VALUES (557, 3, 120);
INSERT INTO "public"."acceso" VALUES (558, 3, 121);
INSERT INTO "public"."acceso" VALUES (559, 3, 122);
INSERT INTO "public"."acceso" VALUES (560, 3, 123);
INSERT INTO "public"."acceso" VALUES (561, 3, 124);
INSERT INTO "public"."acceso" VALUES (562, 3, 125);
INSERT INTO "public"."acceso" VALUES (563, 3, 126);
INSERT INTO "public"."acceso" VALUES (564, 3, 127);
INSERT INTO "public"."acceso" VALUES (565, 3, 128);
INSERT INTO "public"."acceso" VALUES (566, 3, 129);